let tiendaData = [
  {
    id: "jfhgbvnscs",
    nombre: "aiscs EX89",
    precio: 110,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/asicks-shoes.jpg",
  },
  {
    id: "ioytrhndcv",
    nombre: "adidas forum",
    precio: 80,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/adidas-forum.jpg",
  },
  {
    id: "wuefbncxbsn",
    nombre: "Nike dunk",
    precio: 130,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/nike-dunk.jpg",
  },
  {
    id: "thyfhcbcv",
    nombre: "adidas campus 00'",
    precio: 110,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/adidas-00.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    nombre: "Air Jordan 4s Black cat",
    precio: 940,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/jordan-4s-black-cats.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    nombre: "New Balance 2002r",
    precio: 220,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/new-balance-2002r.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    nombre: "Air Jordan 1s Le Maniere",
    precio: 180,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/air-jordan-1.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    nombre: "Asics gel 1130",
    precio: 150,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/aiscs-gel-1130.jpg",
  },
];
